version: '3.4'

services:
  mongodb-primary:
    image: mongo
    ports:
      - 40250:27017
    container_name: mongodb-primary
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${db_root_user}"
      MONGO_INITDB_ROOT_PASSWORD: "${db_root_pass}"

  discordtodoist:
    image: discordtodoist
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5100:5100
    container_name: todoist-integration
    volumes:
      - /var/log:/var/log
    environment:
      - connection_string=mongodb://${db_root_user}:${db_root_pass}@mongodb-primary/
      - todoist_client_id=${todoist_client_id}
      - todoist_client_secret=${todoist_client_secret}
      - todoist_scope=${todoist_scope}
      - discord_token=${discord_token}
      - logging_file=${logging_file}
