version: '3.4'

services:
  app:
    image: todoistintegration
    container_name: todoistintegration
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5100:5100
    volumes:
      - /var/log:/var/log
    environment:
      - connection_string=mongodb://database0:40250,db1:40251,db2:40252/todoist
      - todoist_client_id=${todoist_client_id}
      - todoist_client_secret=${todoist_client_secret}
      - todoist_scope=${todoist_scope}
      - discord_token=${discord_token}
      - logging_file=${logging_file}

  database0:
    image: mongo:6.0
    container_name: database0
    command: mongod --port 40250 --replSet dbrs
    ports:
      - 40250:40250

  db1:
    image: mongo:6.0
    container_name: db1
    command: mongod --port 40251 --replSet dbrs
    ports:
      - 40251:40251

  db2:
    image: mongo:6.0
    container_name: db2
    command: mongod --port 40252 --replSet dbrs
    ports:
      - 40252:40252
