version: '3.4'

services:
  discordtodoist:
    image: discordtodoist
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5100:5100
    container_name: todoist-integration
    volumes:
      - /var/log:/var/log
