version: '3.4'

services:
  app:
    image: todoistintegration
    container_name: todoistintegration
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5100:5100
    volumes:
      - /var/log:/var/log
    environment:
      - connection_string=mongodb://${db_root_user}:${db_root_pass}@database0:40250/
      - todoist_client_id=${todoist_client_id}
      - todoist_client_secret=${todoist_client_secret}
      - todoist_scope=${todoist_scope}
      - discord_token=${discord_token}
      - logging_file=${logging_file}

  database0:
    image: mongo
    container_name: database0
    command: mongod --port 40250
    ports:
      - 40250:40250
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${db_root_user}"
      MONGO_INITDB_ROOT_PASSWORD: "${db_root_pass}"
