name: Deploy
on:
  push:
    branches:
    - develop
    - master
jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          clean: false
      - run: docker build -t todoist-integration:latest .
      - run: docker run -d --name todoist-integration --restart always todoist-integration 
